export type {
  OTPVerificationParams,
  OnboardingStackParamList,
  HomeStackParamList,
  ShopStackParamList,
  EarningStackParamList,
  ProfileStackParamList,
  BottomTabParamList,
  AppStackParamList,
  RootStackParamList,
  OnboardingScreenName,
  HomeScreenName,
  ShopScreenName,
  EarningScreenName,
  ProfileScreenName,
  OnboardingNavigationProp,
  HomeStackNavigationProp,
  ShopStackNavigationProp,
  EarningStackNavigationProp,
  ProfileStackNavigationProp,
  AppStackNavigationProp,
  RootStackNavigationProp,
} from '@/types/navigation.types';
