name: React Native Android Build

on:
  push:
    branches: ['main']

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm install

      - name: Create env file
        run: |
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> .env.staging
          echo "GOOGLE_WEB_CLIENT_ID=${{ secrets.GOOGLE_WEB_CLIENT_ID }}" >> .env.staging

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build APK
        run: npm run build:Staging

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: staging-apk
          path: android/app/build/outputs/apk/staging/release/*.apk
