name: React Native Android Build

on:
  push:
    branches: ['main']

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install

      - name: Create env file
        run: |
          echo "API_BASE_URL=${{ secrets.API_BASE_URL }}" >> .env.production
          echo "GOOGLE_WEB_CLIENT_ID=${{ secrets.GOOGLE_WEB_CLIENT_ID }}" >> .env.production

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ENVFILE=../.env.production ./gradlew assembleProductionRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: production-apk
          path: android/app/build/outputs/apk/production/release/*.apk
